name: Debian package

on: 
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          path: Ejtimaa
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install jq npm build-essential || true
        cd Ejtimaa
        cp server/config/config.example.js server/config/config.js
        cp server/config/config.example.yaml server/config/config.yaml
        cp app/public/config/config.example.js app/public/config/config.js
        cd app
        yarn install && yarn build
        cd ../server
        yarn install && yarn build
        cat <<< $(jq '.bundleDependencies += .dependencies' package.json) > package.json
        npm pack
        VERSION=${{ steps.get-version.outputs.VERSION }}
        DATE=$(date)
        mkdir -p /home/runner/package
        cd /home/runner/package
        mkdir DEBIAN
        mkdir -p usr/local/src/Ejtimaa/server
        mkdir -p etc/systemd/system/
        tar -xf /home/runner/work/***/***/***/server/***-server-$VERSION.tgz package/ 1>/dev/null 2>/dev/null || true
        mv package/* usr/local/src/Ejtimaa/server/
        mv /home/runner/work/***/***/***/*.service etc/systemd/system/
        rm -rf package
        touch DEBIAN/md5sums
        touch DEBIAN/md5sums
        touch DEBIAN/control
        find . -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum  1>/dev/null 2>/dev/null || true
        echo """Package: Ejtimaa-develop
        Version: $VERSION
        Maintainer: Ejtimaa team (https://github.com/Ejtimaa)
        Section: admin
        Date : $DATE
        Architecture: amd64
        Priority: important
        Description: Multiparty web-meetings using mediasoup and WebRTC (develop branch)
        Depends: nodejs (>= 14), redis
        """ > DEBIAN/control
        echo """#!/bin/bash
        mkdir -p /etc/Ejtimaa/
        cp /usr/local/src/Ejtimaa/server/config/config.yaml /usr/local/src/Ejtimaa/server/dist/config/
        ln -s /usr/local/src/Ejtimaa/server/config/config.js /etc/Ejtimaa/server-config.js || true
        ln -s /usr/local/src/Ejtimaa/server/dist/config/config.yaml /etc/Ejtimaa/server-config.yaml || true
        ln -s /usr/local/src/Ejtimaa/server/public/config/config.js /etc/Ejtimaa/client-config.js || true
        systemctl daemon-reload
        systemctl enable Ejtimaa
        echo "Ejtimaa multiparty meeting is installed (develop branch version), but you need the configure the server and client with your ip adresses in configuration files under /etc/meeting/ \n"
        echo "\n\nPlease visit https://github.com/Ejtimaa/Ejtimaa/tree/develop for configuration details.\n\n"
        echo "\n\nAfter the configuration, you can start service with 'sudo systemctl start Ejtimaa' command.\n\n"
        """ > DEBIAN/postinst
        chmod 775 DEBIAN/postinst
        cd ../
        dpkg-deb -Zgzip --build package
        mv /home/runner/package.deb /home/runner/Ejtimaa-develop.deb
    - name : Release Package
      uses: actions/upload-artifact@v2
      with:
        name: Ejtimaa-develop
        path: "/home/runner/Ejtimaa-develop.deb"
